Added Endpoint post and Test for all endpoint
jfgomez86/xr-sinatra pull request #4
Opened 2017-01-27 14:30 UTC by FernandoZX

# SCOPE

Make application have a post endpoint.
Make application have currency model and validation's.
Make project has refactored code.
Make project have test all endpoints.

👍

2017-01-30 20:27 UTC, jfgomez86 requested changes
Por favor asegurate que se pruebe a traves de la url así:

```
get '/USD/to/COP'
```

Para que no se rompa esa funcionalidad.

2017-01-30 20:27 UTC, jfgomez86 commented on app.rb
> +      return text_to_img("not found this currency with code: #{currency}")
Esto falla porque ya no existe ese método. Se elimina en éste mismo PR.

2017-01-30 20:27 UTC, jfgomez86 commented on test/app_test.rb
> +    get '/', :amount => nil, :base => 'USD', :currency => 'COP'
Creo que se debe probar usando la expresión regular. Por ejemplo:

```
get '/USD/to/COP'
```

2017-01-31 14:28 UTC, FernandoZX commented on test/app_test.rb
> +    get '/', :amount => nil, :base => 'USD', :currency => 'COP'
fixed

2017-01-31 14:28 UTC, FernandoZX commented on app.rb
> +      return text_to_img("not found this currency with code: #{currency}")
fixed

2017-01-31 20:17 UTC, merged